### ISSUE TITLE
Whether possible to use the explainer for the other dataset

### ISSUE THREAD

**Issue by ljjsfe** [poloclub/cnn-explainer#10] opened 2020-05-08 04:49 UTC
Hi,

Thank you for sharing this great work. I am new to the Tf.js. I wonder if I finetune the tiny-VGG to the dataset dog vs cat, can the JS automatically to explain the dog vs cat model? Or I have to rewrite the js part. Thx.

**Comment by xiaohk** [comment] 2020-05-08 06:48
Hey, this is a duplicate of #9

**Closed by xiaohk** 2020-05-08 06:48 UTC
