### ISSUE TITLE
Error in running tiny-vgg.py

### ISSUE THREAD

**Issue by ScorpLee** [poloclub/cnn-explainer#21] opened 2020-08-10 15:14 UTC
Hi,

I ran the tiny-vgg.py following the conda env (supposedly all dependencies are installed), and I got error like below.
ValueError: Input 0 of layer sequential is incompatible with the layer: its rank is undefined, but the layer requires a defined rank. 
I'm seeking your thoughts on what is going on. No one else seems have this issue.
Thanks for your time answering this.

**Comment by xiaohk** [comment] 2020-08-15 20:17
Hello @ScorpLee, I just tested to run `tiny-vgg.py` on 758064d9b4121cac14a76f490a39ed61742d6186 on macOS, and I couldn't reproduce the error.

Could you please copy the commands you have run and the error log here? It can help us better troubleshoot it 😃

**Comment by ScorpLee** [comment] 2020-08-17 16:54
Hi,

I ran it on Linux Ubuntu 16.04.6. Please see below screen shot. Thanks for helping.
[cid:image002.png@01D6750A.F04F2610]

Kind regards,

**Comment by xiaohk** [comment] 2020-08-17 17:10
Oops, the screenshot didn't show up in the thread. Maybe you can try to upload it through the GitHub issue website?

**Comment by ScorpLee** [comment] 2020-08-17 21:10
Hi,
I think it has something to do with the system. Maybe I didn't set up the environment properly. I noticed the environment.yaml only has mac-os and windows version. I ran it on windows, too and it was fine. Just wondering if the trained test accuracy is around 67.2000 and test loss 1.1124? I'm not 100% confident. 

The command was: python tiny-vgg.py.

ValueError: in converted code:

    tiny-vgg.py:223 train_step *
        predictions = tiny_vgg(image_batch)
    /usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:586 __call__
        self.name)
    /usr/local/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:111 assert_input_compatibility
        layer_name + ' is incompatible with the layer: '

    ValueError: Input 0 of layer sequential is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

**Comment by xiaohk** [comment] 2020-08-17 22:41
Thanks! Yes, the test accuracy and loss look correct :)

I just tested `tiny-vgg.py` on Ubuntu 16.04.3 and it worked fine. Could you please double check you are using the latest [`environment.yaml`](https://github.com/poloclub/cnn-explainer/blob/master/tiny-vgg/environment.yaml)? I have updated it on the master branch few weeks ago. This environment file should work across different operating systems.

**Comment by xiaohk** [comment] 2020-08-27 04:58
Hey @ScorpLee , I will close the issue for now. Let me know if https://github.com/poloclub/cnn-explainer/issues/21#issuecomment-675150442 didn't help you fix the issue.

**Closed by xiaohk** 2020-08-27 04:58 UTC
